/**
 * Environment Creation Orchestrator
 * Coordinates the creation of Neon database, GitHub repo, and Gitpod workspace
 */

import type {
  Environment,
  ScaffoldContext,
  EnvironmentCreationStep,
} from '@/types/environment';
import { createNeonDatabase } from './neon-client';
import { createGitHubRepo, getGitHubUser, pushFilesToRepo } from './github-client';
import { createGitpodEnvironment } from './gitpod-client';
import { generateScaffold } from './scaffold-generator';

export interface CreateEnvironmentOptions {
  projectName: string;
  projectId: string;
  neonApiKey: string;
  githubToken: string;
  scaffoldContext: ScaffoldContext;
  onProgress?: (progress: number, step: EnvironmentCreationStep, message: string) => void;
}

export interface CreateEnvironmentResult {
  success: boolean;
  environment?: Environment;
  error?: string;
}

/**
 * Create a complete development environment
 *
 * Progress steps:
 * - 0-10%: Creating Neon database
 * - 10-35%: Generating scaffold
 * - 35-55%: Creating GitHub repository
 * - 55-75%: Pushing files to repository
 * - 75-95%: Setting up Gitpod
 * - 95-100%: Complete
 */
export async function createEnvironment(
  options: CreateEnvironmentOptions
): Promise<CreateEnvironmentResult> {
  const {
    projectName,
    projectId,
    neonApiKey,
    githubToken,
    scaffoldContext,
    onProgress,
  } = options;

  const reportProgress = (progress: number, step: EnvironmentCreationStep, message: string) => {
    onProgress?.(progress, step, message);
  };

  try {
    // Step 1: Create Neon Database (0-10%)
    reportProgress(0, 'creating-database', 'Creating Neon PostgreSQL database...');

    const neonEnv = await createNeonDatabase(
      neonApiKey,
      sanitizeProjectName(projectName),
      'aws-us-east-1'
    );

    reportProgress(10, 'generating-scaffold', 'Database created. Generating project scaffold...');

    // Step 2: Generate Scaffold (10-35%)
    const files = generateScaffold({
      ...scaffoldContext,
      projectName: sanitizeProjectName(projectName),
    });

    // Update .env.example with actual connection details (partial, for security)
    const envExampleIndex = files.findIndex((f) => f.path === '.env.example');
    if (envExampleIndex >= 0) {
      files[envExampleIndex].content = generateEnvWithConnection(
        projectName,
        neonEnv.host,
        neonEnv.databaseName
      );
    }

    reportProgress(35, 'creating-repo', 'Scaffold generated. Creating GitHub repository...');

    // Step 3: Create GitHub Repository (35-55%)
    const githubUser = await getGitHubUser(githubToken);
    const repoName = sanitizeRepoName(projectName);

    const githubEnv = await createGitHubRepo(
      githubToken,
      repoName,
      `${projectName} - Generated by PRD-to-Tasks`,
      true // private repo
    );

    reportProgress(55, 'pushing-files', 'Repository created. Pushing project files...');

    // Step 4: Push Files to Repository (55-75%)
    // Wait a moment for GitHub to initialize the repo
    await delay(2000);

    await pushFilesToRepo(
      githubToken,
      githubUser.login,
      repoName,
      files,
      'Initial scaffold generated by PRD-to-Tasks',
      githubEnv.defaultBranch
    );

    reportProgress(75, 'creating-workspace', 'Files pushed. Setting up Gitpod workspace...');

    // Step 5: Create Gitpod Environment (75-95%)
    const gitpodEnv = createGitpodEnvironment(githubEnv.repoUrl);

    reportProgress(95, 'complete', 'Environment creation complete!');

    // Build the final environment object
    const environment: Environment = {
      id: `env-${Date.now()}`,
      projectId,
      projectName,
      status: 'ready',
      neon: neonEnv,
      github: githubEnv,
      gitpod: gitpodEnv,
      createdAt: new Date(),
    };

    reportProgress(100, 'complete', 'Environment ready!');

    return {
      success: true,
      environment,
    };
  } catch (error) {
    console.error('Environment creation failed:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    reportProgress(0, 'error', errorMessage);

    return {
      success: false,
      error: errorMessage,
    };
  }
}

/**
 * Sanitize project name for use as a database name
 */
function sanitizeProjectName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/^_+|_+$/g, '')
    .substring(0, 50);
}

/**
 * Sanitize project name for use as a GitHub repository name
 */
function sanitizeRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-+/g, '-')
    .substring(0, 100);
}

/**
 * Generate .env.example content with connection hints
 */
function generateEnvWithConnection(
  _projectName: string,
  host: string,
  databaseName: string
): string {
  return `# Database (Neon PostgreSQL)
# Replace <password> with your actual password from Neon dashboard
DATABASE_URL="postgresql://neondb_owner:<password>@${host}/${databaseName}?sslmode=require"

# Backend
PORT=3001
NODE_ENV=development

# Frontend
VITE_API_URL=http://localhost:3001/api
`;
}

/**
 * Simple delay utility
 */
function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Re-export client functions for direct use
export { createNeonDatabase, testNeonConnection, deleteNeonProject } from './neon-client';
export {
  createGitHubRepo,
  testGitHubConnection,
  pushFilesToRepo,
  getGitHubUser,
} from './github-client';
export { generateGitpodUrl, openGitpodWorkspace, createGitpodEnvironment } from './gitpod-client';
export { generateScaffold } from './scaffold-generator';
